repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: debug-statements
      - id: check-ast
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: check-yaml
