#!/usr/bin/env python
# -*- coding: utf-8 -*-

# General flags.

LANDING_MODE=True

ENABLED_TICKETS = True
ENABLED_CALL_FOR_PAPERS = True
ENABLED_KEYNOTERS = True
ENABLED_SPEAKERS = True
ENABLED_SPONSORSHIPS = True
ENABLED_SCHEDULE = True
ENABLED_CALL_FOR_SPONSORS = True
ENABLED_BLOG = True
